server:
  port: 8082

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/chatore?options=-c%20timezone=Asia/Kolkata
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true